### PR TITLE
Create Digital clock web app in React.js

### PR DESCRIPTION
**Pull request by syedmaazsaeed**
I will make sure that everything is Clear and precise for You. Please let me know if there is any confusion or if you require any modifications. Please allocate any other problems or assignments you may have in certain repositories to me. I am here to help and you're welcome!

### CODE REVIEW

**Comment by syedmaazsaeed** [comment]
@khaymanii  Bro if everything is okay . Please add my name as a contributor.

**Comment by khaymanii** [comment]
did you create your own branch before making a Pull request?

**Comment by khaymanii** [comment]
you are not suppose to make the changes on an existing folder, you are suppose to create a new folder for "Digital clock" and then put the code there. 
do not make changes to my previous counter app.

**Comment by khaymanii** [comment]
The subfolder you made changes to was already a codebase for a counter app i created,
you are to create another subfolder for the "digital clock app" on the react folder, input your codebase there and then make a PR.

Goodluck.

**Comment by khaymanii** [comment]
Please create a new branch and make your changes do not make commit to the main branch.

**Comment by syedmaazsaeed** [comment]
ok okay

**Pull request closed without merging**
